id: PFD34740D
initial_creation_type: input
source_metadata:
  title: Dharmasamuccaya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: members of the Digital Sanskrit Buddhist Canon Input Project
  contribution to GRETIL: members of the Digital Sanskrit Buddhist Canon Input Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:13:12.069516'
last_modified_at: '2022-03-09T15:13:12.069529'
